const testData = {
  business: [
    {
      businessName: 'Rohan and Sons',
    },
  ],
  users: [
    {
      id: 14,
      userName: 'Khalil Kemmer',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/puzik/128.jpg',
      friendsCount: 383,
      reviewsCount: 68,
      eliteStatus: 0,
    },
    {
      id: 29,
      userName: 'Miss Jeremie Wisoky',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/plbabin/128.jpg',
      friendsCount: 549,
      reviewsCount: 482,
      eliteStatus: 1,
    },
    {
      id: 30,
      userName: 'Sigurd Eichmann',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/jwalter14/128.jpg',
      friendsCount: 509,
      reviewsCount: 370,
      eliteStatus: 1,
    },
    {
      id: 35,
      userName: 'Hunter Davis',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/kudretkeskin/128.jpg',
      friendsCount: 685,
      reviewsCount: 209,
      eliteStatus: 0,
    },
    {
      id: 39,
      userName: 'Mr. Paxton Kunze',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/perfectflow/128.jpg',
      friendsCount: 276,
      reviewsCount: 335,
      eliteStatus: 0,
    },
    {
      id: 41,
      userName: 'Newton Torphy',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/vicivadeline/128.jpg',
      friendsCount: 677,
      reviewsCount: 413,
      eliteStatus: 1,
    },
    {
      id: 42,
      userName: 'Dr. Ila Senger',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/hasslunsford/128.jpg',
      friendsCount: 532,
      reviewsCount: 62,
      eliteStatus: 1,
    },
    {
      id: 45,
      userName: 'Ana Spencer',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/yigitpinarbasi/128.jpg',
      friendsCount: 489,
      reviewsCount: 357,
      eliteStatus: 0,
    },
    {
      id: 49,
      userName: 'Jasmin Ferry',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/strikewan/128.jpg',
      friendsCount: 354,
      reviewsCount: 114,
      eliteStatus: 1,
    },
    {
      id: 50,
      userName: 'Baby Brakus',
      profileImageUrl: 'https://s3.amazonaws.com/uifaces/faces/twitter/kaelifa/128.jpg',
      friendsCount: 708,
      reviewsCount: 75,
      eliteStatus: 0,
    },
  ],
  photos: [
    {
      id: 88,
      businessId: 4,
      imageUploaderId: 14,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/40.jpg',
      imageUploadDate: 'Thu Jul 12 2018 04:56:55 GMT-0700 (PDT)',
      imageComment: 'Inventore corporis et et est qui voluptate itaque et et.',
      helpfulCount: 46,
      reported: 0,
    },
    {
      id: 223,
      businessId: 4,
      imageUploaderId: 29,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/26.jpg',
      imageUploadDate: 'Tue Jun 21 2016 12:53:57 GMT-0700 (PDT)',
      imageComment: 'Eaque iusto dolores aperiam nam est aliquam earum et fugiat.',
      helpfulCount: 8,
      reported: 0,
    },
    {
      id: 300,
      businessId: 4,
      imageUploaderId: 42,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/22.jpg',
      imageUploadDate: 'Mon Aug 24 2015 20:19:04 GMT-0700 (PDT)',
      imageComment: 'Rerum ea animi iure aut et officia dolorem sapiente voluptatem.',
      helpfulCount: 29,
      reported: 0,
    },
    {
      id: 313,
      businessId: 4,
      imageUploaderId: 50,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/9.jpg',
      imageUploadDate: 'Mon Oct 20 2014 00:46:38 GMT-0700 (PDT)',
      imageComment: 'Non voluptas consequatur alias doloribus eos aliquam tempore vitae nisi.',
      helpfulCount: 30,
      reported: 0,
    },
    {
      id: 514,
      businessId: 4,
      imageUploaderId: 45,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/7.jpg',
      imageUploadDate: 'Tue Aug 12 2014 10:14:09 GMT-0700 (PDT)',
      imageComment: 'Ab est aut quod consequatur quaerat voluptates perferendis voluptate harum.',
      helpfulCount: 14,
      reported: 0,
    },
    {
      id: 562,
      businessId: 4,
      imageUploaderId: 30,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/27.jpg',
      imageUploadDate: 'Thu Jun 22 2017 19:38:59 GMT-0700 (PDT)',
      imageComment: 'Inventore ducimus nostrum et nemo architecto et quos aut sed.',
      helpfulCount: 0,
      reported: 0,
    },
    {
      id: 579,
      businessId: 4,
      imageUploaderId: 49,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/8.jpg',
      imageUploadDate: 'Wed Aug 13 2014 14:35:13 GMT-0700 (PDT)',
      imageComment:
        'Id ducimus maxime consequatur temporibus corrupti dolor debitis ea accusantium.',
      helpfulCount: 36,
      reported: 0,
    },
    {
      id: 846,
      businessId: 4,
      imageUploaderId: 39,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/40.jpg',
      imageUploadDate: 'Thu Aug 21 2014 05:52:12 GMT-0700 (PDT)',
      imageComment: 'Qui velit tempora eligendi expedita maxime unde quam minus rerum.',
      helpfulCount: 0,
      reported: 0,
    },
    {
      id: 893,
      businessId: 4,
      imageUploaderId: 41,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/1.jpg',
      imageUploadDate: 'Fri Oct 28 2016 00:19:10 GMT-0700 (PDT)',
      imageComment: 'Ullam distinctio quos minima sit rerum repellendus autem modi sit.',
      helpfulCount: 23,
      reported: 0,
    },
    {
      id: 948,
      businessId: 4,
      imageUploaderId: 35,
      imageUrl: 'https://s3-us-west-1.amazonaws.com/photos-carousel-hr101/41.jpg',
      imageUploadDate: 'Mon May 30 2016 05:49:23 GMT-0700 (PDT)',
      imageComment: 'Qui voluptatibus est qui vel rerum laboriosam possimus sint voluptas.',
      helpfulCount: 36,
      reported: 0,
    },
  ],
};

export default testData;
